name: Tourism Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements-ci.txt

      - name: Register Dataset to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          DATASET_REPO_ID: ${{ secrets.DATASET_REPO_ID }}
        run: python scripts/register_dataset.py

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements-ci.txt

      - name: Data Preparation + Upload train/test
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          DATASET_REPO_ID: ${{ secrets.DATASET_REPO_ID }}
        run: python scripts/data_prep.py

  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements-ci.txt

      - name: Train + Tune + Register Best Model
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          DATASET_REPO_ID: ${{ secrets.DATASET_REPO_ID }}
          MODEL_REPO_ID: ${{ secrets.MODEL_REPO_ID }}
        run: python scripts/train_model.py

  deploy-hosting:
    needs: model-training
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -r requirements-ci.txt

      - name: Push Deployment to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SPACE_REPO_ID: ${{ secrets.SPACE_REPO_ID }}
        run: python scripts/deploy_space.py
