name: Tourism Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements-ci.txt

      # (TEMP) Debug - remove after it works
      - name: Debug - list files
        run: |
          pwd
          ls -la
          ls -la scripts || true
          find . -maxdepth 4 -type f -name "register_dataset.py" -print

      - name: Register Dataset to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          DATASET_REPO_ID: ${{ secrets.DATASET_REPO_ID }}
        run: python tourism_project/scripts/register_dataset.py

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements-ci.txt

      - name: Data Preparation + Upload train/test
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          DATASET_REPO_ID: ${{ secrets.DATASET_REPO_ID }}
        run: tourism_project/scripts/data_prep.py

  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements-ci.txt

      - name: Train + Tune + Register Best Model
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          DATASET_REPO_ID: ${{ secrets.DATASET_REPO_ID }}
          MODEL_REPO_ID: ${{ secrets.MODEL_REPO_ID }}
        run: python tourism_project/scripts/train_model.py

  deploy-hosting:
    needs: model-training
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements-ci.txt

      - name: Push Deployment to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SPACE_REPO_ID: ${{ secrets.SPACE_REPO_ID }}
        run: python tourism_project/scripts/deploy_space.py
